# Worksheet 04

Name:  Prathmesh Sonawane

UID:U39215370

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

In the Minkowski Distance formula, d specified what dimension the data being used are in. In addition, the parameter p is a parameter that specifies what type of distance we are working with, that being the Euclidean,  Manhattan, or other distance. 

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

When calculating the euclidean distance between two points, the distance between two points is the straight line between those points. However, when calculating the Manhattan distance, a data point must travel strictly in the direction of the axes involved in the data. Thus, the Manhattan distance is more strict and often results in a longer distance between points. 


Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

If P were very large, like infinity, distance would probably be more influenced by larger differences in the individual dimensions of the data and less sensitive to smaller differences between the dimensions. In terms of our data, if using a higher p, we would probably find a distance that is closer to the largest difference in terms in our data. 

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

When p <1, it is no longer a distance function since the triangle inequality is violated. For example, when taking the points (0,1), (0,0), and (1,0), if p is less than 1, the distance from (1,0) to (0,1) will be larger than the distance from (1,0) → (0,0) → (0,1). However, the direct distance from (1,0) to (0,1) should be the shortest distance from these two points, creating a contradiction. Thus, when p<1, it is no longer a distance function. 

e) when would you use cosine similarity over the euclidan distance?

We would use the cosine similarity function when the direction of our vectored data matters more to us than the magnitude of that vectored data. In addition, when the size of the documents we are working with largely varies, we should use cosine similarity to more accurately compare and contrast the data, rather than the data’s size. 

f) what does the jaccard distance account for that the manhattan distance doesn't?

When using the Manhattan distance, though two pairs of documents may be the same distance apart, they could be extremely different or similar since we don't take into account the size of each document. Thus, we can use the Jaccard similarity to account for the size of the documents when comparing two documents by incorporating the intersection and union of the data they hold. This allows us to better compare documents with differing sizes. 

#### Part 2

Consider the following two sentences:

In [6]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [7]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [8]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Alice', 'hello', 'is', 'my', 'Bob', 'name']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [9]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [10]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['Alice', 'hi', 'hello', 'is', 'my', 'Claude', 'Bob', 'name']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [16]:
a1 = [1 if x in s1 else 0 for x in all_words] #Represents S1
a2 = [1 if x in s2 else 0 for x in all_words] #Represents S2
a3 = [1 if x in s3 else 0 for x in all_words] #Represents S3

print(str(all_words) + " This is our word bank")
print(str(a1) + " This is s1")
print(str(a2) + " This is s2")
print(str(a3) + " This is s3")

['Alice', 'hi', 'hello', 'is', 'my', 'Claude', 'Bob', 'name'] This is our word bank
[1, 0, 1, 1, 1, 0, 0, 1] This is s1
[0, 0, 1, 1, 1, 0, 1, 1] This is s2
[0, 1, 0, 1, 1, 1, 0, 1] This is s3


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [120]:
def mDistance(x,y):
    if (len(x)!=len(y)):
        raise RuntimeError("X and Y need to be the same dimension")
    sum = 0
    for i in range (len(x)):
        temp = x[i] - y[i]
        if (temp < 0):
            temp = temp * -1
        sum = sum + temp
    return sum

print(str(mDistance(a1,a2)) + " This is a1 and a2")
print(str(mDistance(a2,a3)) + " This is a3 and a2")
print(str(mDistance(a1,a3)) + " This is a1 and a3")
print("As you can see, a1 and a2 are the most similar with this function")
print("those Vectors are " + str(a1) +" and " + str(a2))

2 This is a1 and a2
4 This is a3 and a2
4 This is a1 and a3
As you can see, a1 and a2 are the most similar with this function
those Vectors are [1, 0, 1, 1, 1, 0, 0, 1] and [0, 0, 1, 1, 1, 0, 1, 1]


As we see, v1 and v2 (or the strings s1 and s2) are most similar because their distance from eachother under the manhattan distance formula is lower. 

d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [40]:
r1= "hi Alice"
r2= "hello Claude"
r3= "Bob my name is Claude"
r4= "hi Claude my name is Alice"
r5= "hello Bob"

newCorpus = [r1, r2, r3, r4, r5]
all_new_words = list(set([item for x in newCorpus for item in x.split()]))

row1 = [1 if x in r1 else 0 for x in all_new_words]
row2 = [1 if x in r2 else 0 for x in all_new_words]
row3 = [1 if x in r3 else 0 for x in all_new_words]
row4 = [1 if x in r4 else 0 for x in all_new_words]
row5 = [1 if x in r5 else 0 for x in all_new_words]

#Create the Matrix from the rows 
answer = [row1, row2, row3 , row4, row5]
print("This is our matrix")
print(str(answer))

This is our matrix
[[1, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1], [1, 1, 0, 1, 1, 1, 0, 1], [0, 0, 1, 0, 0, 0, 1, 0]]


e) How many rows and columns does this matrix have?

In [43]:
print("We have " + str(len (answer)) + " rows which equals the number of sentences we use.")
print("We have " + str(len (answer[0])) + " columns which equals the number of distict words we have in our sentences.")

We have 5 rows which equals the number of sentences we use.
We have 8 columns which equals the number of distict words we have in our sentences.


f) When using the Manhattan distance, which two sentences are the most similar?

In [62]:
shortestDistance = -1
saveVector1= []
saveVector2= []

for vector1 in answer: 
    for vector2 in answer: 
        if (vector1 != vector2):
            if ((mDistance(vector1, vector2) < shortestDistance) or shortestDistance <0 ):
                shortestDistance = mDistance(vector1, vector2)
                saveVector1 = vector1
                saveVector2 = vector2

print(saveVector1)
print(saveVector2)
print(shortestDistance)

print("These vectors correspond to \"hello Claude\" and \"hello Bob\".")

[0, 0, 1, 0, 1, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 1, 0]
2
These vectors correspond to "hello Claude" and "hello Bob".


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [119]:
#Input Examples 

import numpy as np

a = np.array([[0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 1], [1, 1, 0, 0, 1, 0], [1, 1, 0, 0, 0, 1], [0, 0, 1, 0, 0, 1], [1, 1, 0, 1, 1, 0]])
b = np.array([[0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 1], [1, 1, 0, 0, 1, 0], [1, 1, 0, 0, 0, 1], [0, 1, 0, 1, 1, 0],[0, 0, 1, 0, 0, 1]])
c = np.array([[0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 1], [1, 1, 0, 0, 1, 0], [1, 1, 0, 0, 0, 1], [0, 1, 0, 1, 1, 0],[0, 0, 1, 0, 0, 1]])
someList = [a,b,c]


#Our Program 
def myfunc(gList):
    length = len (gList) #Get Length of output matrix, the length of the graphs list
    answer = np.zeros((length,length)) #Create answer matrix
    
    #Itterate through all of the graphs
    for i in range (0,len(gList)-1):
        for j in range (i+1, len(gList)):
            graph1 = gList[i]
            graph2 = gList[j]
            
            edgeSum = 0 #Create edge counter
            
            #itterate through both selected graphs and count mutually exclusive edges
            for k in range (len(graph1)):
                for l in range (len(graph1)):
                    if ((graph1[k][l] == 1 and graph2[k][l] == 0) or (graph1[k][l] == 0 and graph2[k][l] == 1)):
                        edgeSum = edgeSum + 1
            
            #Add our count to our answer matrix
            answer[i,j] = edgeSum
            answer[j,i] = edgeSum
    
    return(answer)
                
print(myfunc(someList))


[[ 0. 11. 11.]
 [11.  0.  0.]
 [11.  0.  0.]]
